export const protagonist = {
  name: "林澈",
  age: 22,
  role: "信息管理专业应届生",
  portrait: "澈",
  traits: ["谨慎", "不擅长陌生推销", "愿意把事情做扎实"],
  background:
    "毕业前42天。家里可以继续提供三个月住所，但无法提供创业资金。你曾帮社团整理过报名信息，也会使用常见AI工具。最近，你注意到校园周边的小商户经常漏回客户咨询。",
};

export const hypotheses = [
  {
    id: "pain",
    title: "跟进迟缓正在造成真实损失",
    statement: "本地小商户会因为咨询整理和跟进不及时而丢失客户。",
    prediction: "询问过去发生的具体案例时，店主能说出近期漏单或延迟跟进。",
    stop: "如果相关商户很少发生漏单，或损失不足以改变行为，就停止投入。",
  },
  {
    id: "payment",
    title: "客户愿意为结果付费",
    statement: "至少一类商户愿意为更及时、可靠的客户跟进支付费用。",
    prediction: "在给出明确范围和价格后，客户愿意支付小额定金或试点费用。",
    stop: "如果客户只愿意免费试用，且反复回避价格，就削弱或放弃该假设。",
  },
  {
    id: "delivery",
    title: "AI辅助能够降低交付成本",
    statement: "在人工审核下，AI能让整理与回复流程更快，同时保持可接受的准确性。",
    prediction: "试点中单次处理时间下降，且关键错误能被审核流程拦截。",
    stop: "如果检查成本抵消节省时间，或错误会造成重大损失，就不继续自动化。",
  },
  {
    id: "access",
    title: "熟人入口足够获得首批客户",
    statement: "校园与家庭的弱关系网络足以接触到第一批目标商户。",
    prediction: "通过引荐能完成至少三次与决策者的有效交流。",
    stop: "如果引荐无法到达真正决策者，就必须学习新的获客方式。",
  },
];

export const evidenceCatalog = {
  observedDelay: {
    id: "observedDelay",
    title: "晚回复的咨询记录",
    detail: "你观察到一家店的七条咨询中，有三条超过一天才回复。",
    source: "现场观察",
    strength: 2,
    supports: ["pain"],
    caveat: "只来自一家店，不能代表整个市场。",
  },
  friendPraise: {
    id: "friendPraise",
    title: "熟人店主的积极评价",
    detail: "熟人店主说这个想法‘挺有用’，愿意以后看看。",
    source: "熟人意见",
    strength: 1,
    supports: ["pain", "payment"],
    caveat: "称赞不等于愿意付费，熟人关系也可能让反馈偏积极。",
  },
  pastLosses: {
    id: "pastLosses",
    title: "五位店主的过去行为",
    detail: "五位店主中三位展示了近期漏单记录，两位已经用人工表格补救。",
    source: "目标客户访谈",
    strength: 3,
    supports: ["pain"],
    caveat: "痛点存在，但尚未证明他们愿意购买你的方案。",
  },
  surveyLikes: {
    id: "surveyLikes",
    title: "线上问卷的高兴趣",
    detail: "42人中有31人选择‘愿意尝试AI客户助手’。",
    source: "开放问卷",
    strength: 1,
    supports: ["payment"],
    caveat: "样本身份不明确，表达兴趣与真实购买差距很大。",
  },
  alternatives: {
    id: "alternatives",
    title: "廉价替代方案",
    detail: "市场上已有通用客服工具，但店主认为配置复杂、缺少本地流程支持。",
    source: "竞品研究",
    strength: 2,
    supports: ["delivery", "payment"],
    caveat: "替代品存在意味着客户未必需要你自己开发软件。",
  },
  warmAccess: {
    id: "warmAccess",
    title: "三次有效引荐",
    detail: "学长和家人帮你联系到三位能决定采购的店主。",
    source: "真实引荐",
    strength: 2,
    supports: ["access"],
    caveat: "首批熟人客户不代表以后能持续获客。",
  },
  deposit: {
    id: "deposit",
    title: "300元试点定金",
    detail: "一家培训工作室在看到明确交付范围后支付了定金。",
    source: "真实付款行为",
    strength: 3,
    supports: ["payment"],
    caveat: "一次付款还不能证明稳定需求。",
  },
  pilotUsage: {
    id: "pilotUsage",
    title: "连续七天使用记录",
    detail: "客户持续使用流程，平均响应时间下降，但出现两次需要人工修正的错误。",
    source: "试点行为数据",
    strength: 3,
    supports: ["delivery"],
    caveat: "必须保留人工审核，尚未证明可以规模化。",
  },
  repeatPayment: {
    id: "repeatPayment",
    title: "第二周期续费",
    detail: "客户在没有人情压力的情况下主动续费，并介绍了另一位店主。",
    source: "复购与推荐",
    strength: 3,
    supports: ["payment", "delivery"],
    caveat: "客户数量仍少，业务还没有达到稳定盈利。",
  },
  shopLedger: {
    id: "shopLedger",
    title: "反复补写的咨询账本",
    detail: "账本里有几条隔天补登的家长咨询，但只写了姓名和课程，没有记录最终去向。",
    source: "店内物件",
    strength: 1,
    supports: ["pain"],
    caveat: "补登说明流程可能断裂，却还不能证明因此失单或产生了多大损失。",
  },
  shopMessages: {
    id: "shopMessages",
    title: "停在昨天的未读消息",
    detail: "工作手机上仍有两条昨天发来的课程咨询，其中一位家长已经追问第二次。",
    source: "现场痕迹",
    strength: 2,
    supports: ["pain"],
    caveat: "消息延迟真实存在，但尚不知道客户是否离开、店主是否愿意付费解决。",
  },
  shopQuote: {
    id: "shopQuote",
    title: "被搁置的系统报价单",
    detail: "抽屉里的旧报价单包含十多项功能和年费，却没有写实施人、响应边界和失败责任。",
    source: "既有方案",
    strength: 1,
    supports: ["delivery", "payment"],
    caveat: "一份未成交报价只能提示阻力，不能直接证明客户拒绝的真正原因。",
  },
  shopOwner: {
    id: "shopOwner",
    title: "店主的现实约束",
    detail: "唐曼愿意聊十分钟，但强调高峰期没人配置复杂系统，也不能让AI直接替她承诺课程效果。",
    source: "短时交谈",
    strength: 2,
    supports: ["delivery"],
    caveat: "这是清晰的交付约束，仍需用真实使用与付款行为检验。",
  },
};

export const shopExplorationSpots = [
  {
    id: "ledger",
    label: "补登账本",
    prompt: "柜台下面压着一本经常翻动的账本。",
    x: 67,
    y: 67,
    days: 1,
    money: -10,
    energy: -3,
    evidence: "shopLedger",
    relationship: 1,
    observation: "三条咨询被隔天补写，其中一行只留下‘已加微信’，没有后续状态。",
    inference: "店内的信息流可能在忙碌时断裂；值得追问一次具体咨询后来发生了什么。",
    unknown: "这些空白是否真的造成损失，以及损失是否值得花钱解决。",
    quote: "这不是答案，只是一处需要追下去的断点。",
  },
  {
    id: "messages",
    label: "工作手机",
    prompt: "屏幕亮了一下，两条消息仍停在昨天。",
    x: 47,
    y: 52,
    days: 1,
    money: 0,
    energy: -4,
    evidence: "shopMessages",
    relationship: 0,
    observation: "一位家长在18小时后再次追问试听时间，唐曼还没有来得及回复。",
    inference: "延迟不是泛泛抱怨，而是此刻正在发生的行为事实。",
    unknown: "这位家长会不会流失，以及自动回复是否会比人工延迟更危险。",
    quote: "现在我们至少知道该问哪一次，而不是问她喜不喜欢AI。",
  },
  {
    id: "quotation",
    label: "旧报价单",
    prompt: "抽屉露出一张盖着咖啡印的服务报价。",
    x: 78,
    y: 39,
    days: 1,
    money: 0,
    energy: -2,
    evidence: "shopQuote",
    relationship: 0,
    observation: "报价罗列了智能客服、客户画像等功能，却没写谁来配置、答错后谁负责。",
    inference: "客户可能不是没见过AI方案，而是既有方案没有降低采用与责任风险。",
    unknown: "唐曼当时为何没买：价格、复杂度、责任，还是根本不痛。",
    quote: "先看她已经拒绝过什么，可能比再做一遍演示更值钱。",
  },
  {
    id: "owner",
    label: "忙碌的店主",
    prompt: "唐曼不断在前台、电话和家长之间切换。",
    x: 25,
    y: 48,
    days: 2,
    money: -20,
    energy: -5,
    evidence: "shopOwner",
    relationship: 4,
    requiresClue: true,
    observation: "你用刚才看到的痕迹请求十分钟。唐曼同意，但先划清隐私、承诺和配置时间的边界。",
    inference: "真正可行的方案必须嵌入她的工作方式，并保留人在关键承诺上的责任。",
    unknown: "她会不会为这种可靠流程付款，以及十分钟里最该追问哪一段过去行为。",
    quote: "她不是拒绝技术，她是在保护自己承担不起的后果。",
  },
];

export const actions = [
  {
    id: "observe",
    category: "探索",
    icon: "◌",
    title: "旁观一家店的工作流程",
    description: "花时间看真实咨询怎样进入、被记录和回复。",
    days: 2,
    money: 80,
    energy: 7,
    once: true,
    evidence: ["observedDelay"],
    trustDelta: 1,
    skill: { opportunity: 1, evidence: 1 },
    report: {
      validation: "验证问题是否真的发生，而不是先讨论解决方案。",
      result: "你看见了延迟回复，但样本只有一家店。",
      confirmed: "跟进迟缓至少在这个场景中真实存在。",
      unknown: "它是否普遍，以及损失是否大到值得付费。",
      quote: "先看到真实工作，比听别人说‘市场很大’踏实多了。",
    },
  },
  {
    id: "friendlyInterview",
    category: "探索",
    icon: "◇",
    title: "询问熟人是否喜欢这个想法",
    description: "快速获得鼓励，但问题的设计容易产生礼貌性答案。",
    days: 2,
    money: 40,
    energy: 6,
    once: true,
    evidence: ["friendPraise"],
    skill: { evidence: 0 },
    report: {
      validation: "询问别人是否喜欢一个尚未成形的方案。",
      result: "你得到积极评价，却没有得到过去行为或付款证据。",
      confirmed: "这个表达方式容易被理解。",
      unknown: "客户是否真的痛、是否会付费。",
      quote: "听起来很鼓舞，但我发现自己还是不知道他会不会买。",
    },
  },
  {
    id: "pastBehavior",
    category: "探索",
    icon: "◎",
    title: "访谈五位目标商户",
    description: "只问过去真实发生的漏单、补救与支出，不推销方案。",
    days: 4,
    money: 120,
    energy: 15,
    once: true,
    evidence: ["pastLosses"],
    trustDelta: 2,
    skill: { opportunity: 2, evidence: 2 },
    report: {
      validation: "用过去行为判断问题强度。",
      result: "三位店主能展示漏单，两位已经为补救付出人工成本。",
      confirmed: "问题不是单纯口头抱怨，已有行为证据。",
      unknown: "他们是否愿意把钱付给你。",
      quote: "原来问‘上次什么时候发生’，比问‘你觉得怎么样’有用得多。",
    },
  },
  {
    id: "survey",
    category: "探索",
    icon: "▦",
    title: "发布一份开放式网络问卷",
    description: "覆盖面大，但填答者未必是真正客户。",
    days: 2,
    money: 50,
    energy: 5,
    once: true,
    evidence: ["surveyLikes"],
    report: {
      validation: "用自报兴趣估计购买可能。",
      result: "问卷看起来很漂亮，但证据强度很弱。",
      confirmed: "AI客户助手这个说法能吸引注意。",
      unknown: "谁会在真实预算中为它付费。",
      quote: "数字很多，可我甚至不知道这些人是不是店主。",
    },
  },
  {
    id: "competitors",
    category: "探索",
    icon: "⌁",
    title: "研究现有工具与替代方案",
    description: "了解客户今天怎样解决问题，以及为什么仍然不满意。",
    days: 2,
    money: 0,
    energy: 7,
    once: true,
    evidence: ["alternatives"],
    trustDelta: 1,
    skill: { opportunity: 1, risk: 1 },
    report: {
      validation: "验证客户是否已经有更便宜的替代方案。",
      result: "通用工具很多，但落地配置和持续运营仍然困难。",
      confirmed: "机会可能在服务与流程，而不是再造一个聊天框。",
      unknown: "服务利润能否覆盖持续人工审核。",
      quote: "我差点把‘能做软件’误当成了‘应该做软件’。",
    },
  },
  {
    id: "introductions",
    category: "探索",
    icon: "↗",
    title: "请求三次熟人引荐",
    description: "利用已有关系接触真正能决定采购的人。",
    days: 2,
    money: 0,
    energy: 8,
    once: true,
    evidence: ["warmAccess"],
    trustDelta: 1,
    skill: { opportunity: 1 },
    report: {
      validation: "验证现有关系能否到达首批客户。",
      result: "你获得了三次有效会面，但关系不能无限重复使用。",
      confirmed: "熟人网络足以打开第一扇门。",
      unknown: "陌生市场中的持续获客方式。",
      quote: "这比让我一天敲三十家店的门现实多了。",
    },
  },
  {
    id: "concierge",
    category: "行动",
    icon: "△",
    title: "提出人工辅助的小型试点",
    description: "不先开发系统，用现有工具加人工完成一周服务。",
    days: 3,
    money: 150,
    energy: 11,
    once: true,
    requiresEvidence: 2,
    flags: { proposalReady: true },
    trustDelta: 1,
    skill: { risk: 1, iteration: 1 },
    report: {
      validation: "用最小交付测试客户是否愿意进入真实合作。",
      result: "一家工作室愿意讨论明确范围和价格。",
      confirmed: "可以先卖服务，再决定是否开发产品。",
      unknown: "对方是否会真正付款，以及交付是否划算。",
      quote: "我能接受这个规模。它失败了，我们也还能继续。",
    },
  },
  {
    id: "askDeposit",
    category: "行动",
    icon: "¥",
    title: "先谈范围并收取试点定金",
    description: "把‘感兴趣’推进为带价格的真实承诺。",
    days: 2,
    money: 50,
    energy: 9,
    once: true,
    requires: ["proposalReady"],
    conditional: "deposit",
    skill: { evidence: 2, risk: 1 },
  },
  {
    id: "freePilot",
    category: "行动",
    icon: "□",
    title: "直接免费做完整试点",
    description: "容易开始，但可能验证使用而不是付费意愿。",
    days: 6,
    money: 420,
    energy: 20,
    once: true,
    requires: ["proposalReady"],
    evidence: ["pilotUsage"],
    flags: { pilotDone: true },
    business: { costs: 420, process: 1, reliability: 1 },
    report: {
      validation: "验证客户是否使用，以及交付中会发生什么。",
      result: "客户连续使用，但你投入了大量人工，仍未验证付费。",
      confirmed: "流程能产生价值，也暴露了必须人工审核的错误。",
      unknown: "客户愿意为多少价值付多少钱。",
      quote: "我学到了很多，但免费做下去不是生意。",
    },
  },
  {
    id: "privacy",
    category: "准备",
    icon: "⌾",
    title: "建立数据与人工审核边界",
    description: "限定收集内容、客户授权、删除规则和高风险输出复核。",
    days: 2,
    money: 120,
    energy: 7,
    once: true,
    flags: { privacyReady: true },
    trustDelta: 2,
    skill: { risk: 2 },
    report: {
      validation: "验证方案是否能在不滥用客户数据的条件下运行。",
      result: "你缩小了数据范围，并规定关键回复必须人工确认。",
      confirmed: "可靠性和隐私不是成功以后才补的功能。",
      unknown: "流程扩大后，审核成本是否仍可承受。",
      quote: "如果我们连客户资料都保护不好，就不该要求别人信任我们。",
    },
  },
  {
    id: "paidPilot",
    category: "行动",
    icon: "◆",
    title: "完成一次付费试点",
    description: "交付七天服务，记录耗时、错误、客户使用和业务结果。",
    days: 7,
    money: 500,
    energy: 22,
    once: true,
    requires: ["depositTaken"],
    evidence: ["pilotUsage"],
    flags: { pilotDone: true },
    business: { revenue: 900, costs: 500, paidPilots: 1, process: 1, reliability: 1 },
    skill: { evidence: 2, iteration: 2 },
    report: {
      validation: "同时测试付费、使用、交付成本和AI错误。",
      result: "客户连续使用七天；响应更快，但两次错误被人工审核拦截。",
      confirmed: "客户愿意为这个小范围结果付费。",
      unknown: "能否稳定获客、续费并在计算人工后保持利润。",
      quote: "这是第一份真的证据，不是创业成功证书。",
    },
  },
  {
    id: "process",
    category: "准备",
    icon: "≋",
    title: "只自动化已经重复的步骤",
    description: "把试点中反复出现的工作整理成清单、模板和审核点。",
    days: 4,
    money: 600,
    energy: 15,
    once: true,
    requires: ["pilotDone"],
    flags: { processReady: true },
    trustDelta: 1,
    business: { costs: 600, process: 2, reliability: 1 },
    skill: { risk: 1, iteration: 2 },
    report: {
      validation: "验证混乱交付能否变成可重复流程。",
      result: "单次处理时间下降，关键步骤保留人工复核。",
      confirmed: "先理解流程再自动化，比一次做完整产品更可靠。",
      unknown: "第二位客户是否拥有相同流程。",
      quote: "这次我知道每个自动化步骤为什么存在。",
    },
  },
  {
    id: "renewal",
    category: "行动",
    icon: "∞",
    title: "请求续费并获取转介绍",
    description: "让客户用下一次真实付款证明价值能够持续。",
    days: 4,
    money: 260,
    energy: 14,
    once: true,
    requires: ["pilotDone", "processReady"],
    evidence: ["repeatPayment"],
    flags: { renewed: true },
    trustDelta: 2,
    business: { revenue: 1200, costs: 260, repeatCustomers: 1 },
    skill: { evidence: 2, iteration: 1 },
    report: {
      validation: "验证客户是否愿意持续购买，并主动承担推荐成本。",
      result: "客户续费并介绍了另一位店主。",
      confirmed: "出现了初步的重复需求和口碑入口。",
      unknown: "样本仍少，距离稳定盈利还有获客与容量问题。",
      quote: "这比第一次付款更让我安心，但还不能自称跑通了。",
    },
  },
  {
    id: "fullBuild",
    category: "高风险",
    icon: "▲",
    title: "暂停探索，直接开发完整AI产品",
    description: "十天和大量现金换来一个看似完整的产品。证据不足时可能伤害信任。",
    days: 10,
    money: 2400,
    energy: 25,
    once: true,
    highCommitment: true,
    requiresEvidence: 7,
    conditional: "fullBuild",
  },
  {
    id: "coldOutreach",
    category: "行动",
    icon: "!",
    title: "要求主角一天陌生拜访30家店",
    description: "目标可能合理，但方式严重违背主角当前性格与能力。",
    days: 1,
    money: 0,
    energy: 0,
    once: true,
    conditional: "personalityConflict",
  },
  {
    id: "unsafeData",
    category: "高风险",
    icon: "×",
    title: "偷偷导入客户聊天记录训练流程",
    description: "省去授权沟通，但越过主角的伦理与风险底线。",
    days: 1,
    money: 0,
    energy: 0,
    once: true,
    conditional: "valuesConflict",
  },
  {
    id: "fallback",
    category: "生活",
    icon: "↙",
    title: "保留一次校招面试",
    description: "投入三天准备，降低现金断裂风险，但创业验证会变慢。",
    days: 3,
    money: 80,
    energy: 10,
    once: true,
    flags: { fallbackReady: true },
    skill: { risk: 2 },
    report: {
      validation: "验证保留退路是否会让后续实验更可承受。",
      result: "你获得了一个后续面试机会，也消耗了宝贵的三天。",
      confirmed: "退路本身具有选择权价值。",
      unknown: "面试能否获得录用，以及是否真的需要使用它。",
      quote: "保留退路不是背叛创业，它让我不必把每次试验都当生死局。",
    },
  },
  {
    id: "rest",
    category: "生活",
    icon: "☾",
    title: "休息并整理记录",
    description: "恢复精力，同时用一天把散乱观察写成下一步问题。",
    days: 1,
    money: 80,
    energy: -18,
    repeatable: true,
    skill: { iteration: 1 },
    report: {
      validation: "检验暂停是否能改善判断质量。",
      result: "精力恢复，你也写清了当前最需要验证的问题。",
      confirmed: "休息不是从时间系统里消失，而是在保护未来决策质量。",
      unknown: "机会窗口是否允许更多休息。",
      quote: "我现在没那么想用一个冲动决定解决所有焦虑了。",
    },
  },
];

export const openingLines = [
  "四十二天后，宿舍门卡将失效。",
  "林澈有6800元存款，以及一条尚未被证明的创业线索。",
  "你不是他的控制者。你只能帮助他看见、判断，并提出建议。",
];

export const characters = {
  tangMan: {
    id: "tangMan",
    mark: "唐",
    name: "唐曼",
    role: "青禾培训工作室负责人",
    interest: "减少漏单，但不能承担失控的数据与售后风险",
  },
  xuLan: {
    id: "xuLan",
    mark: "徐",
    name: "徐岚",
    role: "花店店主 · 林澈的熟人",
    interest: "愿意鼓励年轻人，但暂时没有采购预算",
  },
  chengYu: {
    id: "chengYu",
    mark: "程",
    name: "程屿",
    role: "林澈的室友 · 已拿到校招Offer",
    interest: "希望林澈保留现金和就业选择，不把试验变成生死局",
  },
  guYao: {
    id: "guYao",
    mark: "顾",
    name: "顾遥",
    role: "大型平台本地生态经理",
    interest: "寻找能补足平台落地能力的伙伴，同时控制渠道与客户入口",
  },
};

export const storyScenes = [
  {
    id: "complimentAndLedger",
    chapter: "第一幕 · 夸奖与账本",
    title: "两句话都是真的，但用处不同",
    location: "校园商业街 · 下午 16:20",
    cast: ["xuLan", "tangMan"],
    context:
      "徐岚听完林澈的AI客服想法后连连点头。隔壁的唐曼却一边回复家长消息，一边说自己没空聊。两个人似乎给出了相反信号。你只有一次机会决定这次交流怎样继续。",
    dialogue: [
      { speaker: "徐岚", text: "年轻人就应该试试，我觉得这东西肯定有市场。" },
      { speaker: "唐曼", text: "有用当然有用。但你先别给我演示，我今天已经漏回两位家长了。" },
    ],
    choices: [
      {
        id: "askPreference",
        title: "继续询问她们喜不喜欢这个想法",
        description: "容易得到清晰态度，但仍停留在观点和未来承诺。",
        days: 1,
        money: -30,
        energy: -5,
        trust: 0,
        relationships: { xuLan: 6, tangMan: -2 },
        evidence: ["friendPraise"],
        result: {
          title: "更多夸奖，更少确定",
          speaker: "林澈",
          quote: "她们都说喜欢，可我们还是不知道谁损失了什么、谁会付钱。",
          reality: "徐岚愿意以后免费试试；唐曼因为持续被打断，提前结束了谈话。",
          cause: "你收集了观点，却没有追问已经发生的行为和损失。",
          unknown: "真实损失、预算与决策条件仍未出现。",
        },
      },
      {
        id: "inspectPastLoss",
        title: "请唐曼展示最近一次漏单是怎么发生的",
        description: "不推销方案，只还原消息进入、遗漏、补救和损失。",
        days: 2,
        money: -60,
        energy: -9,
        trust: 3,
        relationships: { xuLan: 0, tangMan: 10 },
        evidence: ["pastLosses"],
        skill: { opportunity: 2, evidence: 2 },
        result: {
          title: "账本不会礼貌性赞同",
          speaker: "唐曼",
          quote: "上个月有三位家长问完课就没再回来，其中一位后来去了别家。",
          reality: "唐曼展示了聊天和补登表格；问题真实发生，但她还没有承诺购买。",
          cause: "过去行为把“感觉有用”推进成了可检查的损失链路。",
          unknown: "损失是否足够大、谁有预算、林澈能否可靠交付。",
        },
      },
      {
        id: "demoImmediately",
        title: "抓住注意力，立刻演示完整AI方案",
        description: "展示技术能力，希望漂亮功能直接说服客户。",
        days: 2,
        money: -180,
        energy: -10,
        trust: -3,
        relationships: { xuLan: 3, tangMan: -8 },
        evidence: [],
        result: {
          title: "演示很顺，谈话提前结束",
          speaker: "唐曼",
          quote: "功能我看懂了，但它跟我今天漏掉的两位家长到底有什么关系？",
          reality: "徐岚觉得界面很新鲜；真正忙碌的唐曼没有时间配合配置。",
          cause: "解决方案出现得比问题定义更早，客户只能评价表面功能。",
          unknown: "你仍不知道问题强度、购买条件和现有替代方法。",
        },
      },
    ],
  },
  {
    id: "firstQuote",
    chapter: "第二幕 · 第一份报价",
    title: "客户说“可以试试”之后",
    location: "青禾培训工作室 · 晚上 20:40",
    cast: ["tangMan", "chengYu"],
    context:
      "唐曼愿意给林澈一周时间，但她担心家长数据、AI答错和不断增加的临时需求。程屿提醒林澈：宿舍到期后每个月至少需要2800元生活费。合作能开始，不等于条件已经成立。",
    dialogue: [
      { speaker: "唐曼", text: "要不先都帮我做了？有效果我再考虑付钱。" },
      { speaker: "程屿", text: "免费可以换学习，但你至少要知道自己最多愿意换多少。" },
    ],
    choices: [
      {
        id: "boundedDeposit",
        title: "限定范围、人工审核，并提出300元定金",
        description: "把结果、边界、价格和停止条件放在同一份小试点里。",
        days: 3,
        money: -120,
        energy: -11,
        trust: 4,
        relationships: { tangMan: 8, chengYu: 4 },
        skill: { evidence: 2, risk: 2 },
        conditional: "storyDeposit",
      },
      {
        id: "freeEverything",
        title: "先免费承接所有咨询，再看客户是否满意",
        description: "迅速获得使用反馈，但范围、成本与付费仍然模糊。",
        days: 6,
        money: -520,
        energy: -21,
        trust: -2,
        relationships: { tangMan: 9, chengYu: -5 },
        evidence: ["pilotUsage"],
        flags: { pilotDone: true },
        business: { costs: 520, process: 1, reliability: 1 },
        result: {
          title: "客户满意，你们却没有生意",
          speaker: "程屿",
          quote: "六天都在干活，最后还是不知道她愿意付多少钱。",
          reality: "唐曼持续使用服务；林澈每天人工处理到凌晨，仍未谈价格。",
          cause: "这次行动验证了使用和交付问题，却没有验证交易是否成立。",
          unknown: "真实人工成本、付费意愿和可重复范围仍未解决。",
        },
      },
      {
        id: "promiseAutonomy",
        title: "承诺完全自动化和零错误，先把客户留下",
        description: "用无法验证的承诺绕开审核成本与责任讨论。",
        days: 2,
        money: -260,
        energy: -8,
        trust: -8,
        relationships: { tangMan: -7, chengYu: -4 },
        evidence: [],
        result: {
          title: "一句保证创造了两种风险",
          speaker: "林澈",
          quote: "我没办法保证AI永远不答错，也不想用这种话换来客户。",
          reality: "唐曼追问出错由谁负责，林澈无法回答；你们的协作也出现裂痕。",
          cause: "把尚未解决的可靠性问题藏进承诺，只会放大未来责任。",
          unknown: "缩小范围后是否仍能形成客户愿意购买的结果。",
        },
      },
    ],
  },
];

export const knowledgeNodes = [
  {
    id: "realDemand",
    concept: "demand",
    group: "客户现实",
    title: "抱怨、兴趣与真实损失不是一回事",
    summary: "过去行为、已经付出的补救成本，比口头称赞更接近真实需求。",
    unlockEvidence: ["observedDelay", "pastLosses"],
    keywords: ["漏单", "真实问题", "过去行为", "客户损失", "补救成本", "需求", "痛点"],
  },
  {
    id: "paymentTruth",
    concept: "economics",
    group: "交易结构",
    title: "价值必须进入价格、成本与复购",
    summary: "一次称赞不是生意；付款、交付成本和再次购买共同决定经营是否成立。",
    unlockEvidence: ["deposit", "pilotUsage", "repeatPayment"],
    keywords: ["付费", "定金", "价格", "成本", "利润", "现金流", "复购", "单位经济"],
  },
  {
    id: "commodityShift",
    concept: "substitutes",
    group: "产业变化",
    title: "工具降价会把价值推向可靠结果",
    summary: "当通用AI功能迅速商品化，客户更可能为落地流程、责任和结果付费。",
    unlockEvidence: ["alternatives"],
    unlockFlag: "priceShock",
    keywords: ["工具降价", "同质化", "替代品", "通用工具", "商品化", "平台免费", "功能不值钱"],
  },
  {
    id: "responsibilityGap",
    concept: "responsibility",
    group: "交付边界",
    title: "自动化没有消除责任",
    summary: "错误、隐私和授权会落到具体的人身上；可靠交付必须保留审核与边界。",
    unlockEvidence: ["pilotUsage"],
    unlockFlag: "privacyReady",
    keywords: ["审核", "错误", "可靠", "责任", "隐私", "授权", "数据边界", "人工复核"],
  },
  {
    id: "accessConstraint",
    concept: "distribution",
    group: "市场入口",
    title: "能做出来不等于能持续接触客户",
    summary: "熟人引荐可以打开第一扇门，但规模化需要可重复的获客入口。",
    unlockEvidence: ["warmAccess", "repeatPayment"],
    keywords: ["获客", "渠道", "引荐", "人脉", "客户入口", "触达", "决策者", "转介绍"],
  },
  {
    id: "optionValue",
    concept: "runway",
    group: "生存约束",
    title: "退路让试验不必成为生死局",
    summary: "时间、现金与可承受损失决定你能做多大的验证；退出后仍可在条件改变时回来。",
    unlockFlag: "fallbackReady",
    keywords: ["退路", "止损", "现金", "时间", "风险", "可承受", "退出", "保留选择"],
  },
];

export const worldChallenge = {
  id: "freePlatformShock",
  chapter: "主线挑战 01 · 零价浪潮",
  title: "平台把“AI客服功能”免费了",
  situation:
    "一家大型平台宣布向商户免费开放AI咨询整理。试点客户当晚发来消息：既然工具免费，为什么还要继续付钱给林澈？与此同时，平台正在招募本地服务伙伴，校招窗口也只剩不多的时间。",
  prompt:
    "写下你对局势的理解：真正的客户问题是什么？免费工具改变了什么、没有改变什么？林澈凭什么继续参与，又应把风险控制在哪里？",
  actions: [
    {
      id: "buildProduct",
      icon: "▲",
      title: "追赶平台，开发完整产品",
      description: "用剩余现金押注更多功能，希望在产品层面战胜免费工具。",
      keyConcepts: ["demand", "economics", "substitutes", "responsibility"],
    },
    {
      id: "productizedService",
      icon: "◆",
      title: "收缩为可靠的结果型服务",
      description: "围绕一个客户场景收费交付，用人工审核和流程承担结果。",
      keyConcepts: ["demand", "economics", "substitutes", "responsibility"],
    },
    {
      id: "platformPartner",
      icon: "↗",
      title: "成为平台的本地落地伙伴",
      description: "借用免费工具，把自身位置放在客户入口、配置和持续运营。",
      keyConcepts: ["substitutes", "distribution", "economics", "responsibility"],
    },
    {
      id: "strategicRetreat",
      icon: "↙",
      title: "暂停创业，保留重新进入的条件",
      description: "先恢复现金流并持续观察，不把暂时退出理解为永久失败。",
      keyConcepts: ["runway", "economics", "demand", "substitutes"],
    },
  ],
};

export const challengeOutcomes = {
  buildProduct: {
    weak: {
      title: "巨构空转",
      tone: "failure",
      result: "你们把平台降价理解成了“功能还不够多”。两周后，产品功能增加，客户却没有迁移；现金和校招窗口同时收缩。",
      cause: "行动解决的是技术比较，不是客户愿意付费的剩余问题。",
      lesson: "先确认免费工具仍未解决的责任、流程与交易问题，再决定是否值得产品化。",
      days: 12, money: -2600, trust: -16, process: 1,
    },
    partial: {
      title: "功能追赶",
      tone: "warning",
      result: "你们做出了更贴合本地流程的版本，但持续开发吞噬了交付时间。两位客户愿意试用，仍没人承诺长期购买。",
      cause: "认识到了差异化，却没有先证明这种差异能形成价格与复购。",
      lesson: "把产品拆回可收费的最小流程，用付款决定下一项功能。",
      days: 9, money: -1700, trust: -5, process: 1,
    },
    strong: {
      title: "有序产品化",
      tone: "success",
      result: "你们只开发试点中反复出现的审核与交接步骤，并让首位客户共同验收。工具没有挑战平台，而是降低了已售服务的交付成本。",
      cause: "产品投资建立在真实需求、付款与责任流程之上。",
      lesson: "产品化是已被验证流程的放大器，而不是寻找需求的替代品。",
      days: 7, money: -900, trust: 5, process: 2,
    },
  },
  productizedService: {
    weak: {
      title: "廉价劳务陷阱",
      tone: "failure",
      result: "你们承诺“什么都能代做”，客户不断增加临时要求。看似每天很忙，核算后每单都在亏损。",
      cause: "选择了服务，却没有理解范围、价格、审核责任和单位成本。",
      lesson: "服务不是无限人工；必须定义结果、边界、价格与停止条件。",
      days: 8, money: -780, trust: -10, process: 0,
    },
    partial: {
      title: "有效试点",
      tone: "warning",
      result: "客户愿意继续一个月。你们证明了免费工具仍需要配置与人工审核，但还没解决获客和交付容量。",
      cause: "行动匹配了当前问题，但对持续经营条件的理解还不完整。",
      lesson: "下一步验证复购、转介绍与每单真实人工成本。",
      days: 6, money: 420, trust: 5, process: 1,
    },
    strong: {
      title: "可靠流程",
      tone: "success",
      result: "你们把“及时回复且关键内容有人负责”写进交付范围。客户续费并介绍另一家店，林澈开始拥有可重复的小型业务。",
      cause: "认识与行动共同指向免费功能没有覆盖的可靠结果。",
      lesson: "优势不是拥有AI，而是持续理解场景并对结果负责。",
      days: 6, money: 1100, trust: 8, process: 2,
    },
  },
  platformPartner: {
    weak: {
      title: "平台附庸",
      tone: "failure",
      result: "林澈接受了平台的所有条款，却没有客户关系和议价能力。补贴结束后，订单与收入一起消失。",
      cause: "把接入大平台本身误认为商业成立，没有判断自己控制的客户价值。",
      lesson: "借势之前要明确客户归属、收益结构和可迁移能力。",
      days: 7, money: -360, trust: -9, process: 0,
    },
    partial: {
      title: "借船出海",
      tone: "warning",
      result: "平台带来三次商户接触，林澈完成了两次配置服务。收入有限，但获得了陌生客户样本。",
      cause: "看见了分发价值，尚未建立平台之外的客户关系与复购结构。",
      lesson: "把平台当实验渠道，同时记录可带走的客户认知和流程。",
      days: 5, money: 350, trust: 3, process: 1,
    },
    strong: {
      title: "互补联盟",
      tone: "success",
      result: "林澈只承接平台难以标准化的本地流程，并保留客户沟通与服务续约。平台提供工具和流量，他提供场景理解与责任闭环。",
      cause: "你们准确区分了平台控制的能力与自身可积累的能力。",
      lesson: "合作的关键不是站队，而是互补价值、风险边界与可持续议价权。",
      days: 5, money: 850, trust: 7, process: 1,
    },
  },
  strategicRetreat: {
    weak: {
      title: "错失窗口",
      tone: "failure",
      result: "你们因为“平台太强”停止所有客户交流。两个月后才发现，本地落地服务正在增长，而原有关系已经冷却。",
      cause: "退出来自笼统恐惧，没有区分不可承受风险与仍可低成本验证的未知。",
      lesson: "不参与重投入赛道，不等于停止观察和保留小额选择权。",
      days: 5, money: 0, trust: -5, process: 0,
    },
    partial: {
      title: "保留火种",
      tone: "warning",
      result: "林澈先接受工作机会，每周保留一次客户访谈。现金风险下降，但机会学习速度明显变慢。",
      cause: "判断了生存约束，也保留了重新进入的通道。",
      lesson: "为重新进入设置触发条件：客户主动付款、渠道出现或交付成本显著下降。",
      days: 4, money: 240, trust: 4, process: 0,
    },
    strong: {
      title: "战略等待",
      tone: "success",
      result: "你们停止重投入，却保留已付费客户与每周验证。林澈先获得稳定收入，并约定当复购达到三家时重新全职投入。",
      cause: "退出的是当前风险结构，不是永久关闭创业路径。",
      lesson: "成熟退出包含可观察的重返条件，而不是用恐惧替代判断。",
      days: 4, money: 480, trust: 7, process: 0,
    },
  },
};

export const transferScenarios = {
  baseline: {
    title: "陌生案例 A · AI求职辅导",
    situation:
      "一名应届生会使用AI工具，准备拿6000元做“AI简历与面试辅导”。十位同学都说听起来有用，但还没有人付款。毕业招聘旺季只剩30天，市场上已经有许多免费模板。",
    prompt:
      "在还不知道游戏方法的情况下，请写下：你认为他还缺少哪些认识？第一步应该做什么？什么情况出现时应该停止或改变方向？",
  },
  post: {
    title: "迁移案例 B · 餐饮短视频服务",
    situation:
      "一名离职设计师有12万元积蓄，想给小餐馆提供AI短视频服务。五位朋友都说画面不错，一家餐馆愿意免费试用。平台刚推出一键生成模板，而设计师不擅长陌生销售。",
    prompt:
      "不要复述上一局答案。请为这个新人物设计：仍需补足的认识、最小验证行动、风险上限，以及在什么证据出现后继续、转向或退出。",
  },
};

export const transferDimensions = [
  {
    id: "reality",
    label: "真实问题",
    description: "区分口头评价与过去行为、实际损失。",
    keywords: ["过去行为", "真实问题", "损失", "痛点", "上一次", "实际发生", "谁需要"],
  },
  {
    id: "payment",
    label: "交易证据",
    description: "关注价格、付款、预算或复购，而非只看兴趣。",
    keywords: ["付费", "付款", "定金", "预算", "价格", "复购", "购买"],
  },
  {
    id: "experiment",
    label: "最小验证",
    description: "用访谈、小范围试点或其他低成本行动换取信息。",
    keywords: ["访谈", "小范围", "试点", "最小", "低成本", "先验证", "少量客户", "测试"],
  },
  {
    id: "economics",
    label: "交付经济",
    description: "核算时间、人工、获客与单位成本。",
    keywords: ["成本", "利润", "人工", "耗时", "获客", "现金流", "单位经济", "交付"],
  },
  {
    id: "risk",
    label: "责任风险",
    description: "识别错误、隐私、授权和人格能力边界。",
    keywords: ["错误", "隐私", "授权", "责任", "审核", "边界", "不擅长", "能力"],
  },
  {
    id: "alternatives",
    label: "环境替代",
    description: "理解竞品、免费工具和环境变化改变了什么。",
    keywords: ["竞品", "替代", "免费", "平台", "模板", "同质化", "差异化", "环境"],
  },
  {
    id: "stopping",
    label: "止损与重返",
    description: "设置时间、金额和证据触发的继续、转向或退出条件。",
    keywords: ["止损", "停止", "退出", "转向", "上限", "最多", "期限", "重新进入", "触发条件"],
  },
];
